### ISSUE TITLE
bug with One Auth NoPad.png

### ISSUE THREAD

**Issue by thecoder876** [onedotprojects/cdn#1]
[![bug screenshot](https://user-images.githubusercontent.com/76265544/113747905-c7eda800-96ff-11eb-91ec-2afd4539cdc3.png)](https://cdn.onedot.cf/brand/PNG/One%20Auth%20NoPad.png)
cc @wgyt

**Comment by RedGuy12** [comment]
No, it’s a bug with the links. They have a preceding slash like “/Transparent” instead of “Transparent” which makes each link go back a directory.

**Comment by thecoder876** [comment]
> No, it’s a bug with the links. They have a preceding slash like “/Transparent” instead of “Transparent” which makes each link go back a directory.

@RedGuy12 oh ok

**Comment by wgyt** [comment]
> No, it’s a bug with the links. They have a preceding slash like “/Transparent” instead of “Transparent” which makes each link go back a directory.

we can fix this and I have a fix in the back of my head, will make a pr
