### ISSUE TITLE
make a onehost build

### ISSUE THREAD

**Issue by wgyt** [onedotprojects/cdn#4]
this won't be hard because 1host uses the node http module just like this.
we just have to replace a few lines (So we use res.start and don't use res.end)

**Comment by thecoder876** [comment]
@wgyt wdym a special version of 1cdn for 1host?

**Comment by wgyt** [comment]
> @wgyt wdym a special version of 1cdn for 1host?

Yeah, but it would be pretty similar to the regular build

**Comment by thecoder876** [comment]
> > *[ping removed]* wdym a special version of 1cdn for 1host?
> 
> Yeah, but it would be pretty similar to the regular build

@wgyt ok

**Comment by wgyt** [comment]
Question about this, should we use the default error handler in 1Host for this or should we use the one build in to the non 1Host build?

**Comment by wgyt** [comment]
1host is dead
